[IMP] SUITE account payment return: Improvements to suite
OCA/account-payment pull request #107
Opened 2016-10-25 11:50 UTC by carlosdauden

- Add raise "You can not be removed a payment return if state is 'Done'".

- New SEPA return code.

- Add check to match returns after import.

@Tecnativa

2016-10-25 11:59 UTC, pedrobaeza requested changes

2016-10-25 11:59 UTC, pedrobaeza commented on account_payment_return/models/payment_return.py
> +                "You can not be removed a payment return if state is 'Done'"))
Remove `be`

2016-10-25 11:59 UTC, pedrobaeza commented on account_payment_return_import/i18n/es.po
> +"No se pudo hacer con sentido de el archivo dado.\n"
Trato de usted, no de tú

2016-10-25 11:59 UTC, pedrobaeza commented on account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml
> +        <field name="name">Disputed authorised transaction</field>
This isn't translated?

2016-10-25 12:20 UTC, carlosdauden commented on account_payment_return_import/i18n/es.po
> +"No se pudo hacer con sentido de el archivo dado.\n"
Leo cosas contradictorias al respecto, por eso nunca lo tengo claro...

2016-10-25 12:20 UTC, carlosdauden commented on account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml
> +        <field name="name">Disputed authorised transaction</field>
https://github.com/OCA/account-payment/pull/107/files#diff-e37f5160827a396976dac1201391ad64R61

2016-10-25 12:37 UTC, pedrobaeza commented on account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml
> +        <field name="name">Disputed authorised transaction</field>
OK

2016-10-25 12:38 UTC, pedrobaeza commented
Include a test for unlinking returns for not dropping coverage

2016-10-25 16:45 UTC, carlosdauden commented
@pedrobaeza changes done

2016-10-25 16:48 UTC, carlosdauden commented
cc @sergio-teruel

2016-10-25 17:00 UTC, pedrobaeza commented
Please don't squash while the review process. You only need to squash before merging (when the PR is approved), or it's more difficult to track changes from one review to the next. Reviewer can indicate you if you need to squash or not.

2016-10-25 17:01 UTC, pedrobaeza commented
You have to test also a case where there's no error and the payment can be removed.

2016-10-25 17:25 UTC, pedrobaeza approved these changes
Thanks for the changes.

To the merger: squash on merging

2016-10-26 07:19 UTC, rafaelbn approved these changes
OK! Thanks

2016-10-26 07:22 UTC, sergio-teruel approved these changes
Ok..

2016-10-26 07:43 UTC, yajo requested changes

2016-10-26 07:43 UTC, Yajo commented on account_payment_return/models/payment_return.py
> +        return super(PaymentReturn, self).unlink()
I'd implement this as a [global ir.rule](https://www.odoo.com/documentation/8.0/reference/security.html#record-rules) instead.

2016-10-26 08:05 UTC, carlosdauden commented on account_payment_return/models/payment_return.py
> +        return super(PaymentReturn, self).unlink()
It is an option, but usually this is the way used and possibly better performance.

2016-10-26 09:47 UTC, pedrobaeza commented on account_payment_return/models/payment_return.py
> +        return super(PaymentReturn, self).unlink()
The problem is the overlapping of access rules that grants you at the end the unlink. This has to be the way.

2016-10-26 09:47 UTC, pedrobaeza commented
Merging

2016-10-26 09:48 UTC, merged

2016-10-26 14:07 UTC, Yajo commented on account_payment_return/models/payment_return.py
> +        return super(PaymentReturn, self).unlink()
Well, I know it's late and after all it works fine this way, but just to clarify, I meant a *global* rule. Quoting from the above link:

> Global rules are subtractive, they must all be matched for a record to be accessible

2016-10-26 14:46 UTC, pedrobaeza commented on account_payment_return/models/payment_return.py
> +        return super(PaymentReturn, self).unlink()
OK, thanks for clarifying. Odoo doesn't do this kind of things by security rules, so there should be a reason for that. Maybe performance as pointed by Carlos, or maybe to not bypass this check removing access rule.