[9.0][MIG] account_due_list_payment_mode: Migrate to V9
OCA/account-payment pull request #118
Opened 2016-12-11 10:43 UTC by sergio-teruel

This PR depends of https://github.com/OCA/account-payment/pull/101

cc @tecnativa

2016-12-11 10:53 UTC, pedrobaeza requested changes

2016-12-11 10:53 UTC, pedrobaeza commented on account_due_list_payment_mode/__init__.py
>  # -*- encoding: utf-8 -*-
coding

2016-12-11 10:53 UTC, pedrobaeza commented on account_due_list_payment_mode/__openerp__.py
>  # -*- encoding: utf-8 -*-
coding

2016-12-11 10:53 UTC, pedrobaeza commented on account_due_list_payment_mode/models/__init__.py
>  # -*- encoding: utf-8 -*-
coding

2016-12-11 10:53 UTC, pedrobaeza commented on account_due_list_payment_mode/views/payment_view.xml
> +            <filter string="Month" icon="terp-go-month" domain="[]"
Put only `<filter context="{'group_by':'date_maturity'}"` as selector

2016-12-11 10:53 UTC, pedrobaeza commented on account_due_list_payment_mode/views/payment_view.xml
> +        <field name="name">Payments Mode Select</field>
Don't put name on inherited views.

2017-02-23 15:46 UTC, pedrobaeza commented
@sergio-teruel please make the requested changes

2017-03-27 00:23 UTC, mileo commented on account_due_list_payment_mode/views/payment_view.xml
> +        <field name="name">Payments Mode Select</field>
@pedrobaeza You are sayng to don't use an explict name just a namespace like:

https://github.com/OCA/account-analytic/blob/10.0/account_analytic_no_lines/views/account_analytic_account.xml#L8

```
<record model="ir.ui.view" id="account_analytic_account_form_view">
        <field name="name">account.analytic.account.form (in account_analytic_no_lines)</field>
        <field name="model">account.analytic.account</field>
        <field name="inherit_id" ref="analytic.view_account_analytic_account_form"/>
        <field name="arch" type="xml">
            <xpath expr="//div[@name='button_box']/button[@name=%(analytic.account_analytic_line_action)d]" position="attributes">
                <attribute name="groups">account_analytic_no_lines.hide_analytic_entries</attribute>
            </xpath>
        </field>
    </record>
```

In this case
```
<field name="name">account.move.select (in account_due_list_payment_mode)</field>
```

cc: @vonpupp

2017-03-27 00:26 UTC, mileo commented
LGTM, after correcting Baeza's comments.

2017-03-27 06:09 UTC, pedrobaeza commented on account_due_list_payment_mode/views/payment_view.xml
> +        <field name="name">Payments Mode Select</field>
I say that for avoiding extra translation and lines, as this name is useless and it's auto-generated if not explicitly added, but you can put it if you want.

2017-03-27 14:44 UTC, pedrobaeza approved these changes

2017-03-27 16:04 UTC, lreficent commented
Runbot is having issues with the account_due_list dependency, does this need a rebase?

2017-03-27 16:10 UTC, pedrobaeza commented
It seems so. Rebased to see the result.

2017-03-28 15:03 UTC, vonpupp commented
PR #129 seems to address that issue. I will try it later.

2017-03-30 12:16 UTC, vonpupp commented
I have created a simple [buildout] for testing purposes. Please use the branch `9-mig-account_due_list_payment_mode`. I tested the installation and it seems ok.

[buildout]: https://github.com/vonpupp/testpr-buildout

2017-03-30 14:55 UTC, luismontalba approved these changes
Tested on runbot

2017-03-30 18:01 UTC, mileo approved these changes

2017-03-30 18:01 UTC, mileo commented
Tested on runbot

2017-04-03 19:45 UTC, vonpupp commented
I believe this is ready for merge @pedrobaeza, isn't it?

2017-04-04 20:04 UTC, merged