[9.0] [MIG] account_due_list_aging_comments
OCA/account-payment pull request #124
Opened 2016-12-29 15:24 UTC by jbeficent

Account Due List Aging Comments
===============================

This module extends the Payments and Due list to add the capability to
introduce aging comments in-line.

Usage
=====

To use this module, you need to go to:

* Accounting->Journal Entries->Payments and due list

2017-01-18 15:20 UTC, AaronHForgeFlow approved these changes
LGTM despite minor comments :+1:

2017-01-18 15:20 UTC, aheficent commented on account_due_list_aging_comments/views/payment_view.xml
> +    <data>
\<openerp\> now is \<odoo\> and remove \<data\>

2017-01-18 15:20 UTC, aheficent commented on account_due_list_aging_comments/views/payment_view.xml
> +
I would introduce the field in the form view also

2017-01-18 15:40 UTC, LoisRForgeFlow approved these changes
tested on local :+1:

2017-04-14 00:56 UTC, max3903 requested changes

2017-04-14 00:56 UTC, max3903 commented on account_due_list_aging_comments/README.rst
> +* Accounting->Journal Entries->Payments and due list
Accounting -> Adviser ->Payments and due list

2017-04-14 00:58 UTC, max3903 commented on account_due_list_aging_comments/README.rst
> +* Accounting->Journal Entries->Payments and due list
@jbeficent `account_due_list` needs to depend on `account_accountant` to have access to the Adviser submenu (see #135)

2017-04-14 15:42 UTC, lasley commented on account_due_list_aging_comments/__openerp__.py
> +    'version': '9.0.0.2.0',
9.0.1.0.0

2017-04-25 10:43 UTC, jbeficent commented on account_due_list_aging_comments/README.rst
> +* Accounting->Journal Entries->Payments and due list
Done!

2017-04-25 10:43 UTC, jbeficent commented on account_due_list_aging_comments/__openerp__.py
> +    'version': '9.0.0.2.0',
Done!

2017-04-25 10:44 UTC, jbeficent commented
@max3903 @lasley your review comments have been attended. Do you agree to merge this one now?

2017-04-25 14:34 UTC, lasley approved these changes
LGTM - one minor thing I probably should have noticed the first time around, but nothing blocking

2017-04-25 14:34 UTC, lasley commented on account_due_list_aging_comments/__openerp__.py
> +              'Eficent',
I would recommend to put yourself first here.

2017-04-25 22:17 UTC, max3903 approved these changes

2017-04-25 22:34 UTC, merged