[10.0][MIG] account_payment_show_invoice
OCA/account-payment pull request #150
Opened 2017-06-16 16:47 UTC by mreficent

Standard migration.

2017-06-19 07:58 UTC, LoisRForgeFlow approved these changes
:+1:

2017-10-02 14:06 UTC, rami-wafaie approved these changes
Review + functional testing
:+1:

2017-10-02 14:07 UTC, rami-wafaie commented
@pedrobaeza Can you please have a look at this?

2017-10-02 14:14 UTC, adrienpeiffer requested changes

2017-10-02 14:14 UTC, adrienpeiffer commented on account_payment_show_invoice/models/account_payment.py
> +class ModelName(models.Model):
s/ModelName/AccountPayment

2017-10-10 15:41 UTC, pedrobaeza commented
@adrienpeiffer can you update your review?

2017-10-10 16:28 UTC, adrienpeiffer approved these changes
:+1:

2017-10-10 16:30 UTC, merged