[10.0][IMP] Add both pivot and graph views to account_due_list
OCA/account-payment pull request #185
Opened 2018-04-19 13:11 UTC by robyf70

Just to improve the account due list representation and pivoting

2018-04-19 13:25 UTC, jackjack82 approved these changes
fine for me

2018-04-20 15:43 UTC, feketemihai approved these changes

2018-04-27 02:10 UTC, agb80 commented
:+1: pretty usefull and easy improvement

2018-04-27 11:24 UTC, pedrobaeza commented
Please change module version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

And where are the definition of those views?

2018-04-27 13:38 UTC, robyf70 commented
@pedrobaeza The views aren't really necessary, defaults are pretty ok for me. Will increase the version number right now

2018-04-27 13:40 UTC, pedrobaeza commented
But you should create them with the same defaults, or this module will not be inheritable as dependent modules might create other conflicting views instead of inheriting the main one.

2018-04-27 14:54 UTC, robyf70 commented
@pedrobaeza I've just pushed a new rebased patch with related pivot and graph views

2018-04-27 14:58 UTC, robyf70 commented
@pedrobaeza Sorry! Wrong patch, will resubmit

2018-04-27 15:09 UTC, robyf70 commented
@pedrobaeza Now looks fine

2018-04-27 15:18 UTC, pedrobaeza requested changes
And what about graph view?

2018-04-27 15:18 UTC, pedrobaeza commented on account_due_list/views/payment_view.xml
> +    <record model="ir.actions.act_window.view" id="view_payments_tree_action">
Not needed

2018-04-27 15:18 UTC, pedrobaeza commented on account_due_list/views/payment_view.xml
> +    <record model="ir.actions.act_window.view" id="view_payments_pivot_action">
Not needed.

2018-04-27 16:03 UTC, robyf70 commented
@pedrobaeza ok! I've done some changes and added the missing graph view, let me know if now looks ok for you

2018-04-27 17:41 UTC, pedrobaeza approved these changes

2018-05-16 07:28 UTC, adrienpeiffer approved these changes
👍

2018-05-16 08:50 UTC, merged

2018-05-16 08:51 UTC, pedrobaeza commented
Cherry-picked for v11 in b2addc3