[MIG] account_payment_batch_process
OCA/account-payment pull request #190
Opened 2018-05-31 01:22 UTC by faryrosa

#161 
[MOD]Including translation for Dominican Republic
[MOD]The amount to text calculation is replaced
[MOD]Change in the search for keys in the dictionary
[MOD]Setting in the default_get method call in AccountRegisterPayments
[MOD]Adjust in the view to guarantee read-only fields storage

2018-06-01 15:01 UTC, faryrosa commented
Okay, I'm working on the changes. Thank you

2018-06-19 11:15 UTC, pedrobaeza commented
Can you put a more appropriated title and what this does?

2018-06-20 12:33 UTC, faryrosa commented
When I make the changes I modify the description with your suggestions

2018-07-07 18:52 UTC, hbto commented on .vscode/settings.json
> +}
This folder/file includes absolute paths to your folders.

Regards

2018-08-14 22:09 UTC, max3903 requested changes

2018-08-14 22:09 UTC, max3903 commented on account_payment_batch_process/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
@faryrosa Can you use the new readme structure from:
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-08-15 05:43 UTC, bodedra requested changes
Please respect commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

2019-05-07 05:14 UTC, kittiu commented
The name should be like [11.0][MIG] account_payment_batch_process ?

2019-05-07 05:23 UTC, kittiu commented
@faryrosa would you also add more test? :)

2019-05-07 10:03 UTC, faryrosa commented
Hello

I apologize, but I could not advance more in this migration.

On Tue, May 7, 2019 at 1:23 AM Kitti U. <notifications@github.com> wrote:

> @faryrosa <https://github.com/faryrosa> would you also add more test? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/account-payment/pull/190#issuecomment-489913047>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AITQQ3A2ASF5JWJCANUJQNLPUEG6BANCNFSM4FCRCUJQ>
> .
>

2019-05-21 22:22 UTC, max3903 commented
Thanks @faryrosa. @murtuzasaleh will take it from here.

2019-05-21 22:22 UTC, closed without merging

2019-05-22 10:42 UTC, murtuzasaleh commented
> Thanks @faryrosa. @murtuzasaleh will take it from here.

#255