[11.0][account_partner_reconcile] splits the button 'Match payments' to 'Match Receivables' and 'Match payables'
OCA/account-payment pull request #219
Opened 2019-02-04 18:32 UTC by jbeficent

The previous button was just now working in v11.

2019-02-05 11:22 UTC, MiquelRForgeFlow requested changes

2019-02-05 11:22 UTC, mreficent commented on account_partner_reconcile/models/res_partner.py
> +            accounts = self.self.property_account_payable_id
self.self.

2019-02-05 16:09 UTC, Nikul-Chaudhary reviewed
Improved Code

2019-02-05 16:09 UTC, Nikul-Chaudhary commented on account_partner_reconcile/models/res_partner.py
> +            accounts = self.self.property_account_payable_id
It's Simplify, No need to else

```
accounts = self.property_account_payable_id
if reconcile_mode == 'customers':
    accounts = self.property_account_receivable_id
```

2019-05-28 08:31 UTC, MiquelRForgeFlow approved these changes
LGTM

2019-05-28 13:20 UTC, mreficent commented
@pedrobaeza ready to merge :green_apple:

2019-05-28 13:40 UTC, LoisRForgeFlow approved these changes

2019-05-28 14:33 UTC, merged