[12.0] [MIG] account_due_list_aging_comment
OCA/account-payment pull request #225
Opened 2019-02-20 08:49 UTC by cor9003

Migration to 12 account_due_list_aging_comment

2019-02-20 09:08 UTC, cor9003 commented
Hello, The CLA has been already signed ans dent by email

2019-02-25 16:25 UTC, Nikul-Chaudhary commented on account_due_list_aging_comment/__manifest__.py
> +    'website': 'http://www.eficent.com',
@cor9003 URL `https://github.com/OCA/account-payment`

2019-04-24 19:20 UTC, tbaden requested changes
please use the [maintainer-tools](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0) to create readme.

2019-04-28 18:38 UTC, cor9003 commented
@tbaden readme created with maintainer-tools. Thanks to inform me

2019-04-28 18:40 UTC, tbaden commented
Thanks for the work 👍
Just the request from @Nikul-Chaudhary is still open

2019-04-28 19:46 UTC, cor9003 commented on account_due_list_aging_comment/__manifest__.py
> +    'website': 'http://www.eficent.com',
Done !

2019-04-28 19:55 UTC, cor9003 commented
@tbaden The request from @Nikul-Chaudhary is already done

2019-04-28 19:56 UTC, tbaden approved these changes
Thanks, please Squash your commits into 1

2019-05-01 19:37 UTC, cor9003 commented
squash commits into 1 done. @tbaden Is there any action I should do to move forward this PR?

2019-05-01 19:51 UTC, tbaden commented
@Nikul-Chaudhary anymore changes or good to go?

2019-05-25 03:34 UTC, cor9003 commented
@Nikul-Chaudhary @tbaden Hello, do I have to do anything to move forward this PR ?

2019-06-06 11:53 UTC, MiquelRForgeFlow requested changes
Please, maintain commit history as explained here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0.

To save your work, you can copy the folder and paste outside the repo. Then reset the branch to v12.0, apply what in the link says in order to put add all commit history. And then copy the previous copied folder and paste in the repo overwriting it, and commit and push force.

2019-06-07 13:56 UTC, cor9003 commented
@mreficent I do not have the branch 12.0 in my forked repository and I don´t know how add this branch 12.0 in my forked repository. I would prefer delete this pull request and start from scratch and give you a clear new pull request. Is it ok for you ?

2019-06-07 14:40 UTC, mreficent commented
ok. do as you prefer. to create branches, you can always do:

git fetch origin 12.0
git checkout -b new_branch origin/12.0

2019-06-08 08:29 UTC, closed without merging