[10.0] account_check_printing_report_base - fix paid amount
OCA/account-payment pull request #261
Opened 2019-05-31 11:08 UTC by jbeficent

The report showed the total paid amount, of the invoice, not the amount paid by the specific payment.

2019-05-31 14:41 UTC, max3903 approved these changes

2019-06-03 07:24 UTC, AaronHForgeFlow approved these changes
:+1:

2019-06-03 09:42 UTC, AaronHForgeFlow requested changes
Not working for supplier payments

2019-06-03 09:56 UTC, aheficent commented
It seems to me that this fix is the same as https://github.com/OCA/account-payment/pull/259/ :thinking:

2019-06-03 13:43 UTC, jbeficent commented
cc @max3903 can you please consider the new changes? This is a significant refactor.

2019-06-03 19:19 UTC, max3903 approved these changes

2019-06-05 13:23 UTC, AaronHForgeFlow approved these changes
:+1:  Functional tests

2019-06-05 13:38 UTC, merged

2019-06-05 13:43 UTC, mreficent commented
travis ci was red :S

2019-06-14 04:03 UTC, jbeficent commented
@aheficent can you incorporate these changes into 11.0 and 12.0 (https://github.com/OCA/account-payment/pull/241)