[12.0][MIG] account_check_printing_report_sslm102
OCA/account-payment pull request #288
Opened 2019-10-29 15:24 UTC by MiquelRForgeFlow

Standard migration.

2019-10-29 17:37 UTC, AaronHForgeFlow requested changes
>  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_check_printing_report_sslm102_invoice_data_478
TypeError: 'NoneType' object is not callable

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: account_check_printing_report_sslm102.invoice_data
Path: /templates/t/div/strong/span[2]
Node: <span name="payment_date" style="padding-right:100mm;float:right;" t-esc="'Date: {}'.format(_format_date_to_partner_lang(o.payment_date, o.partner_id.id))"/>
                

When printing: http://3393814-288-afe5ce.runbot3.odoo-community.org/web?debug=true#id=2&action=140&active_id=7&model=account.payment&view_type=form&menu_id=82

2019-10-29 18:03 UTC, MiquelRForgeFlow commented on account_check_printing_report_sslm102/views/report_check.xml
> +                        <div name='top_block' style="position:absolute; top:15mm; left:10mm;">
@hveficent could you check if this template needs a wkhtmltopdf 0.12.5 revamp like done in https://github.com/OCA/account-payment/pull/212?

2019-10-30 12:20 UTC, HviorForgeFlow requested changes

2019-10-30 12:20 UTC, hveficent commented on account_check_printing_report_sslm102/views/report_check.xml
> +                <span t-esc="_format_date_to_partner_lang(o.payment_date, o.partner_id.id)"/>
Functional review - Error found @mreficent 
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_check_printing_report_sslm102_invoice_data_1326
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 711, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 751, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 534, in render_template
    return view_obj.render_template(template, values)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1304, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/OCB-12.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1313, in render
    return self.env[engine].render(self.id, qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 348, in _compiled_fn
    raise e
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_717_1313
  File "<template>", line 2, in body_call_content_1312
  File "<template>", line 5, in foreach_1311
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_check_printing_report_sslm102_invoice_data_1326
TypeError: 'NoneType' object is not callable

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: account_check_printing_report_sslm102.invoice_data
Path: /templates/t/div/strong/span[2]
Node: <span name="payment_date" style="padding-right:100mm;float:right;" t-esc="'Date: {}'.format(_format_date_to_partner_lang(o.payment_date, o.partner_id.id))"/>
```

2019-11-08 18:30 UTC, mreficent commented on account_check_printing_report_sslm102/views/report_check.xml
> +                <span t-esc="_format_date_to_partner_lang(o.payment_date, o.partner_id.id)"/>
solved

2019-11-08 18:31 UTC, mreficent commented on account_check_printing_report_sslm102/views/report_check.xml
> +                        <div name='top_block' style="position:absolute; top:15mm; left:10mm;">
@hveficent could you apply wkhtmltopdf 0.12.5 revamp, please?

2019-11-13 16:10 UTC, hveficent commented on account_check_printing_report_sslm102/views/report_check.xml
> +                        <div name='top_block' style="position:absolute; top:15mm; left:10mm;">
@mreficent for now it is ok! Let users decide how to apply styling on demand :smile:

2019-11-13 16:10 UTC, HviorForgeFlow approved these changes

2019-11-13 16:12 UTC, MiquelRForgeFlow reviewed
:+1:

2019-11-13 16:18 UTC, AaronHForgeFlow approved these changes
Tested. LGTM :+1:

2019-11-22 11:32 UTC, aheficent commented
Ready to merge

2020-01-08 11:36 UTC, JordiBForgeFlow commented
/ocabot merge

2020-01-08 12:09 UTC, merged