[13.0] [MIG] Partner Aging
OCA/account-payment pull request #297
Opened 2019-12-12 10:07 UTC by nikul-serpentcs

Interactive Partner Aging at any date
=====================================

This module creates new customer/supplier aging as of a given date.

The default Aged Partner balance report is related to a specific date and a
static PDF that is based on the difference between credits and debits, not
based on documents such as Invoices and Payments.
This module provides an interactive view with details of the invoice.
This module does not consider unapplied credits.

2019-12-12 13:23 UTC, nikul-serpentcs commented
@max3903 @smangukiya Can you please review it?

2019-12-13 16:35 UTC, smangukiya requested changes
apart from those minor changes. It LGTM.

2019-12-13 16:35 UTC, smangukiya commented on partner_aging/__manifest__.py
> +# Copyright 2012 Open Source Integrators
Can you please change the Copyright from 2012 to 2019 on all the files?

2019-12-20 04:19 UTC, nikul-serpentcs commented
@max3903 @smangukiya Can you please update your review?

2019-12-26 21:15 UTC, max3903 approved these changes

2019-12-26 21:16 UTC, max3903 commented
/ocabot merge

2019-12-26 21:28 UTC, merged