[13.0] [MIG] account_payment_return_import_iso20022: Migration to v13
OCA/account-payment pull request #346
Opened 2020-09-10 15:11 UTC by victoralmau

@Tecnativa TT19693

Please @pedrobaeza review it

2020-09-11 17:00 UTC, pedrobaeza commented
@sbidoul why this weird ping to a non maintainer?

2020-09-11 17:03 UTC, pedrobaeza requested changes
I haven't continued, but restore all the docstrings. See https://www.python.org/dev/peps/pep-0257/ for knowing more about docstring that seems that you don't like, hehe.

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/__manifest__.py
> +    "version": "13.0.1.1.0",
```suggestion
    "version": "13.0.1.0.0",
```

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/__manifest__.py
>      "development_status": "Production/Stable",
You can change it to mature:
```suggestion
    "development_status": "Mature",
```

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/tests/test_import_iso20022.py
> +    # Run test to import payment return import
Don't change docstring by comments

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/tests/test_import_iso20022.py
> +        # Test correct creation of single payment return
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/tests/test_import_iso20022.py
> +        # Test import of multiple statements from zip file
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/tests/test_import_iso20022.py
> +        # Test correct creation of single payment return
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/tests/test_import_iso20022.py
> +        # Test import of multiple statements from zip file
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +    # Parser for CAMT Bank to Customer Debit Credit Notification
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +        # Parse element that contains Amount
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +        # Parse element that contains date
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +        # Parse transaction details
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +        # Parse transactions (entry) node
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/camt_parser.py
> +        # Parse entry node.
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/pain_parser.py
> +    # Parser for SEPA Direct Debit Unpaid Report import files
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/pain_parser.py
> +        # Parse element that contains Amount and CreditDebitIndicator
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/pain_parser.py
> +        # Parse element that contains date
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/pain_parser.py
> +        # Parse transaction details
Restore it

2020-09-11 17:03 UTC, pedrobaeza commented on account_payment_return_import_iso20022/wizard/pain_parser.py
> +        # Parse transaction (entry) node
Restore it

2020-09-14 07:14 UTC, pedrobaeza approved these changes
You may want to rebuild README file with the OCA tool

2020-09-14 12:36 UTC, victoralmau commented
Sorry @pedrobaeza  but i'not regenerate readme yet with OCA tool. Can you regenerate it when oca bot apply the changes?

2020-09-14 13:22 UTC, pedrobaeza commented
OK, bot can do it on merge. It was just for seeing the changes directly.

2020-09-14 15:14 UTC, carlosdauden approved these changes

2020-09-14 15:15 UTC, pedrobaeza commented
/ocabot merge nobump

2020-09-14 15:30 UTC, merged