[13.0] [IMP] account_check_printing_report_base: Add letter format to A4 checks
OCA/account-payment pull request #368
Opened 2020-11-04 15:15 UTC by CarlosRoca13

@sergio-teruel @carlosdauden  This are the format improvements for promissory notes

cc @Tecnativa TT25536

2020-11-06 17:15 UTC, pedrobaeza commented
Please rebase to get possible green Travis

2020-11-06 17:18 UTC, pedrobaeza requested changes

2020-11-06 17:18 UTC, pedrobaeza commented on account_check_printing_report_base/i18n/es.po
> +msgstr "Querido proveedor"
```suggestion
msgstr "Estimado proveedor"
```

2020-11-06 17:18 UTC, pedrobaeza commented on account_check_printing_report_base/i18n/es.po
> +msgstr "Mostrar Nombre"
It was previously correct

```suggestion
msgstr "Nombre mostrado"
```

2020-11-06 17:18 UTC, pedrobaeza commented on account_check_printing_report_base/i18n/es.po
> +msgstr "Fecha de Vencimiento"
Upper letters must follow standard Spanish rules (no upper in the middle of a sentence except the known exceptions)

```suggestion
msgstr "Fecha de vencimiento"
```

2020-11-10 07:10 UTC, CarlosRoca13 commented
@pedrobaeza All changes done

2020-11-10 08:10 UTC, pedrobaeza approved these changes

2020-11-10 08:23 UTC, victoralmau approved these changes

2020-11-10 08:27 UTC, pedrobaeza commented
/ocabot merge patch

2020-11-10 10:03 UTC, merged