[14.0][MIG] Migrated a partner_aging module.
OCA/account-payment pull request #408
Opened 2021-04-14 04:43 UTC by AmmarOfficewalaSerpentCS

2021-04-14 05:49 UTC, AmmarOfficewalaSerpentCS commented
@murtuzasaleh , @max3903 , @dreispt , @nikul-serpentcs 

Can you please review this PR ?

2021-05-18 21:18 UTC, patrickrwilson requested changes
Very small cleanup changes. I also noticed that the python/xml shows formatting that pre-commit usually complains about but is green in this PR. I wonder if pre-commit isn't configured the same as in other repo's? or it's changed since run on this PR? 

If it's green after fixing these small changes it should be good to go.

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/wizards/res_partner_aging_supplier.xml
> +<?xml version="1.0" encoding="utf-8"?>
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/wizards/res_partner_aging_date.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/wizards/res_partner_aging_customer.xml
> +<?xml version="1.0" encoding="utf-8"?>
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/wizards/__init__.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/tests/test_partner_aging.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/tests/__init__.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/__manifest__.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-05-18 21:18 UTC, patrickrwilson commented on partner_aging/__init__.py
> +# -*- coding: utf-8 -*-
This line is no longer needed (Since v11)

2021-06-09 16:45 UTC, patrickrwilson approved these changes
LGTM

2021-06-09 16:45 UTC, patrickrwilson commented
@osi-scampbell Can you assist with reviewing this PR?

2021-06-09 17:31 UTC, osi-scampbell commented on partner_aging/__manifest__.py
> +    "maintainers": ["smangukiya"],
@AmmarOfficewalaSerpentCS do you want to add yourself down here?

2021-06-09 17:33 UTC, osi-scampbell commented on partner_aging/wizard/res_partner_aging_date.py
> +        return True
@AmmarOfficewalaSerpentCS why do we have this 'return True' line here? Will it ever be hit? If not, then I don't believe we need it

2021-06-09 17:35 UTC, osi-scampbell commented on partner_aging/wizard/res_partner_aging_date.py
> +        return True
@AmmarOfficewalaSerpentCS Same question as before, how does this 'return True' line get hit? If 'self' is null? I am not sure if that case will ever happen will it?

2021-07-19 18:42 UTC, max3903 approved these changes

2021-07-19 18:46 UTC, max3903 commented
/ocabot merge nobump

2021-07-19 19:00 UTC, merged