[MIG][15.0] account_payment_return
OCA/account-payment pull request #536
Opened 2022-08-25 14:40 UTC by ChrisOForgeFlow

@ForgeFlow

2022-09-01 06:57 UTC, DavidJForgeFlow requested changes
Functional Review :+1:, one change in Readme and done!

2022-09-01 06:57 UTC, DavidJForgeFlow commented on account_payment_return/README.rst
> +#. Go to Invoicing > Sales > Customer Payment Returns, and create a new
Invoicing > Customers > Customer Payment Returns

2022-09-22 10:00 UTC, ValentinVinagre commented
@ChrisOForgeFlow Can you check the comments? thanks 😄

2022-09-30 12:08 UTC, ChrisOForgeFlow commented
> @ChrisOForgeFlow Can you check the comments? thanks smile

Done!, thanks

2022-11-28 16:29 UTC, victoralmau requested changes

2022-11-28 16:29 UTC, victoralmau commented on account_payment_return/tests/test_payment_return.py
> +class TestPaymentReturn(SavepointCase):
```suggestion
from odoo.tests.common import Form, TransactionCase


class TestPaymentReturn(TransactionCase):
```

2022-11-29 14:45 UTC, victoralmau commented
Can you merge your changes in a single commit (migration commit)?

2023-02-06 10:57 UTC, carlosdauden requested changes

2023-02-06 10:57 UTC, carlosdauden commented on account_payment_return/models/payment_return.py
> +            "account_id": self.journal_id.default_account_id.id,
Use Outstanding Receipts Account

2023-03-14 07:32 UTC, ao-landoo commented
@ChrisOForgeFlow are you continuing with this PR?

2023-03-14 08:22 UTC, carlosdauden commented
As there was no response I am preparing a new PR

2023-03-14 11:55 UTC, ChrisOForgeFlow commented
> As there was no response I am preparing a new PR
Sorry, I can continue with PR, are you agree?

2023-03-20 00:10 UTC, carlosdauden commented
https://github.com/OCA/account-payment/pull/610

2023-03-21 00:10 UTC, closed without merging