ADD Voucher invoices Number - Display linked invoices in voucher list
OCA/account-payment pull request #55
Opened 2015-12-10 17:22 UTC by eLBati

This module extends voucher list view in order to display the invoices linked to every voucher

2016-05-26 15:01 UTC, amoya-dx commented
:+1:

2016-06-29 13:15 UTC, dufresnedavid commented on account_voucher_invoice_number/models/account_voucher.py
> +            invoices_str += invoice.number
Sorry, I am not a fan of such string values. I think this is some kind of dupplication of information.
Why not only displaying invoice_ids as many2many_tag ?

2016-06-29 13:18 UTC, dufresnedavid commented on account_voucher_invoice_number/models/account_voucher.py
> +        compute=_compute_invoices)
you can pass compute as a string. compute='_compute_invoices'. This would make more easy to inherit your module.

2016-06-29 13:19 UTC, dufresnedavid commented
@eLBati few comments. I think this module is useful. Also, can you add the .png file for the icon ?

2017-07-28 07:57 UTC, pedrobaeza commented
Is this still relevant?

2017-07-28 11:22 UTC, dufresnedavid commented
:+1:

2017-07-28 11:28 UTC, pedrobaeza commented
@eLBati there are 2 comments remaining.

2017-07-28 12:29 UTC, dufresnedavid commented
@pedrobaeza you can merge

2017-07-28 23:39 UTC, pedrobaeza requested changes
Remove standard icon SVG

2017-07-31 06:46 UTC, eLBati commented
> Remove standard icon SVG

🤔 why?

2017-07-31 07:00 UTC, pedrobaeza commented
* The icon should be in PNG.
* The SVG should only be included if there's any modification over the standard one, which is stored in https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg.

2017-08-07 14:44 UTC, eLBati commented
@pedrobaeza oops I didn't notice both png and svg were there. Removed svg

2017-08-07 14:45 UTC, pedrobaeza approved these changes

2017-08-07 14:51 UTC, merged