Add account_cash_discount_reconcile_write_off
OCA/account-payment pull request #674
Opened 2023-10-13 13:23 UTC by FranzPoize

2023-10-26 13:24 UTC, hparfr requested changes
please squash in one commit

2023-10-26 13:24 UTC, hparfr commented on account_cash_discount_reconcile_write_off/README.rst
> +* ACSONE SA/NV
please fix !

2023-10-26 13:24 UTC, hparfr commented on account_cash_discount_reconcile_write_off/__manifest__.py
> +    "author": "ACSONE SA/NV," "Odoo Community Association (OCA)",
here too

2023-10-26 13:24 UTC, hparfr commented on account_cash_discount_reconcile_write_off/readme/USAGE.rst
> +#. Adds a invoice that has a cash discount
typo

2023-10-26 14:14 UTC, nayatec commented on account_cash_discount_reconcile_write_off/__manifest__.py
> +# Copyright 2018 ACSONE SA/NV
pls fix

2023-10-26 14:16 UTC, nayatec commented on account_cash_discount_reconcile_write_off/README.rst
> +#. Add a partner that has a invoice with a cash discount to a payment
typo : an invoice

2023-10-26 14:16 UTC, nayatec commented on account_cash_discount_reconcile_write_off/README.rst
> +#. Adds a invoice that has a cash discount
typo : Add an invoice

2023-10-26 14:18 UTC, nayatec requested changes
Pls fix (see comments)

2023-10-27 07:19 UTC, hparfr approved these changes
A part from the typo in the readme; it's good to me

Thanks @FranzPoize !

2023-10-27 07:59 UTC, nayatec approved these changes
LGTM thks !

2023-11-29 16:06 UTC, FranzPoize commented
Hi @pedrobaeza could you merge this please ?

2023-11-29 17:59 UTC, pedrobaeza commented
Merging due to the existing reviews:

/ocabot merge nobump

2023-11-29 18:09 UTC, merged