[16.0][MIG] account_payment_term_discount Migration to V16.0
OCA/account-payment pull request #737
Opened 2024-06-13 16:39 UTC by ChrisOForgeFlow

Superseed: https://github.com/OCA/account-payment/pull/687

2024-06-13 16:55 UTC, MiquelRForgeFlow approved these changes

2024-06-14 12:18 UTC, JordiBForgeFlow approved these changes

2024-06-14 12:18 UTC, JordiBForgeFlow commented on account_payment_term_discount/README.rst
> +* Add landed costs by selecting the landed cost product and entering the
Does this make sense in this context?

2024-06-14 13:37 UTC, GuillemCForgeFlow requested changes

2024-06-14 13:37 UTC, GuillemCForgeFlow commented on account_payment_term_discount/views/account_payment_term_view.xml
> +            </xpath>
```suggestion
            <xpath expr="/form/sheet/group/group/field[@name='name']" position="after">
                <field name="is_discount" />
                <field name="is_exclude_shipping_lines" attrs="{'invisible': [('is_discount', '=', False)]}"/>
                <field name="is_exclude_taxes_discount" attrs="{'invisible': [('is_discount', '=', False)]}" />
            </xpath>
```
For UX purposes, we could make the two fields that depend on the `is_discount` to be True to be shown + maybe putting them into a separate group? I guess the first point would make sense, right? Perhaps I'm missing something.

2024-06-14 18:59 UTC, JordiBForgeFlow commented
/ocabot merge nobump

2024-06-14 19:05 UTC, merged