[15.0][IMP] account_payment_notification - show bank name on email templates for vendor bills
OCA/account-payment pull request #766
Opened 2024-10-28 11:20 UTC by edlopen

This will show the bank name on emails when it's a payment for a vendor.

@moduon MT-7146

@Shide @yajo @rafaelbn please review, if you can.

2024-10-28 11:48 UTC, Shide requested changes

2024-10-28 11:48 UTC, Shide commented on account_payment_notification/data/mail_template.xml
> +
```suggestion
<br/>
```

Now looks like this:
![image](https://github.com/user-attachments/assets/5b60d1c8-1c53-4df5-a9bb-20b9b59381ca)

2024-10-28 12:39 UTC, Shide approved these changes

2024-10-30 10:32 UTC, yajo approved these changes
/ocabot merge minor

2024-10-30 10:39 UTC, merged