[14.0][MIG] account_payment_promissory_note: Migration to 14.0
OCA/account-payment pull request #770
Opened 2024-11-21 11:11 UTC by unaiberis

2025-01-02 11:29 UTC, anajuaristi approved these changes

2025-01-02 11:31 UTC, rlizana approved these changes
LGTM :+1:

2025-01-02 11:38 UTC, anajuaristi commented
@rlizana Thank you for your review. 

@pedrobaeza, @JordiBForgeFlow @etobella @StefanRijnhart this is a backport from V15. 
Could you please review and merge? 

Thank you!! and Happy new year!!

2025-01-02 11:43 UTC, pedrobaeza requested changes
It seems the commits are a bit mangled, mixing in the migration to 14.0 commit things that are not of the migration itself.

2025-01-02 11:43 UTC, pedrobaeza commented on account_payment_promissory_note/README.rst
> +  * César A. Sánchez
Why this name is added in this commit?

2025-01-02 11:43 UTC, pedrobaeza commented on account_payment_promissory_note/__manifest__.py
> +    "version": "14.0.1.0.2",
Incorrect version. It should be `14.0.1.0.0`

2025-01-02 11:43 UTC, pedrobaeza commented on account_payment_promissory_note/i18n/account_payment_promissory_note.pot
> +"Project-Id-Version: Odoo Server 15.0\n"
Why this change here in this commit?

2025-01-02 11:43 UTC, pedrobaeza commented on account_payment_promissory_note/i18n/es.po
> +msgstr "Mezcla de pagarés"
These changes mustn't be in the migration commit.

2025-01-02 12:07 UTC, unaiberis commented on account_payment_promissory_note/README.rst
> +  * César A. Sánchez
The pre-commit added it automatically. I have removed it

2025-01-02 12:08 UTC, unaiberis commented on account_payment_promissory_note/i18n/es.po
> +msgstr "Mezcla de pagarés"
I have added a new commit for this change

2025-01-02 12:12 UTC, pedrobaeza commented
@unaiberis I think you mix the commit history, as pre-commit is not adding names randomly to READMEs. Please start from scratch following carefully the procedure and avoiding to squash commits that shouldn't be squashed.

2025-01-02 12:53 UTC, unaiberis commented
> @unaiberis I think you mix the commit history, as pre-commit is not adding names randomly to READMEs. Please start from scratch following carefully the procedure and avoiding to squash commits that shouldn't be squashed.

I think now I have done it correctly. I added a commit for the migration process and another commit for the translation, which was missing in version 13.0

2025-01-02 15:11 UTC, pedrobaeza reviewed
It still seems that you have taken the changes from https://github.com/OCA/account-payment/commit/e333cb3b09bb699501e921d31e356c45b9d84c78 in the migration to 15.0, and include it in your 14.0 migration commit, which is not correct.

You should cherry-pick the commit as is, and then perform on top of it the little adaptations to 14.0.

2025-01-03 10:13 UTC, unaiberis commented
> It still seems that you have taken the changes from [e333cb3](https://github.com/OCA/account-payment/commit/e333cb3b09bb699501e921d31e356c45b9d84c78) in the migration to 15.0, and include it in your 14.0 migration commit, which is not correct.
> 
> You should cherry-pick the commit as is, and then perform on top of it the little adaptations to 14.0.

Now I have maintainted the commits of the migration to the version 15.0 to show it is a backport from that specific version.

2025-01-03 17:22 UTC, pedrobaeza commented on account_payment_promissory_note/readme/CONTRIBUTORS.rst
> +  * Berezi Amubieta
You can't add 3 names for such simple migration.

2025-01-28 08:08 UTC, anajuaristi commented on account_payment_promissory_note/readme/CONTRIBUTORS.rst
> +  * Berezi Amubieta
@pedrobaeza 
Is it correct now?
We need this merged asap
Thank you

2025-01-28 08:11 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-01-28 08:22 UTC, merged